services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: nest-docker-postgres
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/app # Permet de monter le projet dans le container pour le hot-reloading
      - /app/node_modules
    depends_on:
      - db

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    privileged: true

  # pour tester prometheus
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - monitoring

  # pour récupérer les perf des containers
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    privileged: true

  # Pour visualiser les données de prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3001:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  grafana_data: