# Ce dockefile est utilisé pour le développement. 
# On peut y ajouter le hot-reloading pour la rapidité et le confort
# Peut utiliser les montages de volumes pour synchroniser les modifs en la machine et le container afin d'éviter de rebuild l'image

FROM node:23

WORKDIR /app

# Copier les fichiers nécessaires
COPY package*.json ./
COPY .env.local ./

# Installer les dépendances
RUN npm install

# Charger les variables d'environnement
RUN export $(grep -v '^#' .env.local | xargs)

RUN npm run seed

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
