server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
  filesystem:
    directory: /tmp/loki/chunks

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  max_label_names_per_series: 64
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false

compactor:
  working_directory: /tmp/loki/compactor

ingester:
  wal:
    enabled: false

ring:
  kvstore:
    store: memberlist
    prefix: loki/
    consistency_level: block
  replication_factor: 1
