---
- name: Installer les dépendances nécessaires
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Ajouter la clé GPG de Doppler
  shell: |
    curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/doppler-archive-keyring.gpg

- name: Ajouter le dépôt de Doppler au fichier sources.list
  shell: echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | tee /etc/apt/sources.list.d/doppler-cli.list
  args:
    creates: /etc/apt/sources.list.d/doppler-cli.list

- name: Mettre à jour les paquets et installer Doppler
  apt:
    name: doppler
    state: present
    update_cache: yes